# Generated by Django 5.0.2 on 2026-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_updated_at_property_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='uploads/properties/'),
        ),
    ]
